language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - v7
  - v6
script:
  - npm run test:unit
  - npm run test:lint
after_success:
  - npm run semantic-release
