language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - v8
before_install:
  - npm install -g @patrickhulce/scripts
script:
  - npm test
after_success:
  - hulk npm-publish --yes
